### PR TITLE
Not a clue

### PR DESCRIPTION
**Pull request by CatalystCoder**
I'm at a loss at this point and I may be overthinking things. What happens when I try to do a rackup on it I get a page that says: 

ArgumentError at /
wrong number of arguments (given 0, expected 1)
file: string_segmenter.rb location: segment_string line: 5

And I'm not sure why it's encountering that error. Any and all help appreciated! The String segmenter code works on its own.

### CODE REVIEW

**Comment by sumeetjain** [comment]
It means:

You're calling a method `segment_string` and giving it zero arguments. But the method requires that you give it 1 argument.

**Comment by CatalystCoder** [comment]
it's now telling me that my method is not defined but I never changed the method. This is the specific error though. NoMethodError at /num
undefined method `segment_string' for #MyApp:0x007f96709d3948
file: main_controller.rb location: block in <top (required)> line: 18

**Comment by sumeetjain** [comment]
Here's exactly what I need to help you learn to debug:
1. When you encounter any unsatisfactory situation, immediately commit your code and push to GitHub. The commit message can be "ugh"–for example.
2. Then add a comment to your PR with the following information:
   - What precisely you were trying to do.
   - What the error text, if any, was.
   - If there wasn't any error text, describe whatever there _was_.

**Comment by CatalystCoder** [comment]
Done with the basics but there's some extra code in here that I'm working with so might want to ignore those parts as they're a work in progress.
